### ISSUE TITLE
[RFE] Add support to encrypt file content and file names

### ISSUE THREAD

**Issue by aruiz** [rianhunter/dbxfs#1]
It'd be great if it could encrypt new data and decrypt remote objects  as well as its names keeping only the tree structure exposed.

This would allow the usage of Dropbox storage space without giving up access to the content. All clients would have to share the key to encrypt and decrypt and if you loose the keys that'd be problematic. (Integration with LastPass or 1Password could mitigate that)

**Comment by rianhunter** [comment]
This is already implemented in a separate project that I haven't released yet. How interested are you in that feature?

**Comment by wharlox** [comment]
I can think of many ways to complicate the encryption process; I'd be interested to see what you have so far.
I'd go crazy and encrypt each folder/file uniquely with its own passphrases (especially if integrated with LastPass or 1Password)

**Comment by rianhunter** [comment]
@wharlox The key is per-folder. Filenames are encrypted using a pure function (so you lose semantic encryption) but data are encrypted using random IVs.

**Comment by TheOneHyer** [comment]
I definitely second this feature, especially on a per-folder basis. That lets one encrypt personal folders but not shared folders or folders meant to be shared with a phone.

**Comment by rianhunter** [comment]
Cool, I need to clean up my code a little bit but I can release a pretty straightforward per-folder encryption layer that I've been using. Can't say when, might be in about a month. The more people that comment will speed up the process :)

**Comment by nicko7i** [comment]
I do this with [encfs](https://en.wikipedia.org/wiki/EncFS).  For example:
```
% mkdir ~/crypt
% mkdir ~/mydropbox/crypt
% encfs ~/mydropbox/crypt ~/crypt
```

I select the pre-configured "paranoia" mode.  Provide a passphrase, and everything you do in ~/crypt is reflected, encrypted, in ~/mydropbox/crypt

You can get *encfs* from the package manager of most distros.

**Comment by tkossak** [comment]
@nicko7i looks awesome, I must try it, thank you!

**Comment by nicko7i** [comment]
@rianhunter At first I thought they were nested, but in fact they are not.  The FUSE mount is the cleartext  ~/crypt directory. Thanks.

**Comment by wolfgang-noichl** [comment]
Wouldn't it be easier to just put https://github.com/rfjakob/gocryptfs on top of dbxfs? It already has these futures, and it's been around for a while. It also has the advantage that you can have it on top of normal Dropbox as well, so you're not bound to one client.

**Comment by rianhunter** [comment]
Closing because existing solutions exist for this and I am not releasing an encryption layer any time soon if ever.
