### ISSUE TITLE
App Key and App Secret Exposed

### ISSUE THREAD

**Issue by peterfarrell** [rianhunter/dbxfs#11]
https://github.com/rianhunter/dbxfs/blob/master/dbxfs/main.py#L57-L59

Was it your intent to expose the app key and app secret?

**Comment by rianhunter** [comment]
yes, this is recommended by dropbox

**Comment by peterfarrell** [comment]
Thanks for the feedback. Usually when I see things like this, it's accidentally being exposed which why I asked. Maybe a comment above those lines in the code will help eliminate any future questions?

**Comment by rianhunter** [comment]
yeah i was thinking that after your comment

**Comment by rianhunter** [comment]
btw thanks for going out of your way to open this pull request :)
