### ISSUE TITLE
Libreoffice unable to open files read-write

### ISSUE THREAD

**Issue by lukefor** [rianhunter/dbxfs#13]
It seems that Libreoffice is unable to create its lockfile within dbxfs - getting the following when attempting to open a file within dropbox:

![image](https://user-images.githubusercontent.com/283772/46905862-a70eb800-cef1-11e8-9f51-7175bfbb6fd4.png)

Disabling file locking successfully works around the issue: https://askubuntu.com/questions/553824/how-to-disable-locking-in-libreoffice

I'm using Libreoffice 6.1 on Debian 9

(As an aside, great job on this project, really glad to have a dropbox client that works natively on ARM and doesn't require ext4!)

**Comment by rianhunter** [comment]
Fixed by 22d8b49
