### ISSUE TITLE
Folder creation returns failure, but actually succeeds

### ISSUE THREAD

**Issue by JeffPsycle** [rianhunter/dbxfs#15]
I have found a problem while scripting to create folders for importing files. The paths below are renamed from what we actually use.

The script is very simple, just looping through folders to copy over:

```
DBPATH="/home/dbuser/dropbox"
PATH=$1
/usr/bin/find $PATH -type d | while read FILE

do

    CHECKPATH=$(/usr/bin/echo "${FILE}" | /usr/bin/sed -e "s&${PATH}&${DBPATH}&g")

    /usr/bin/sudo -u dbuser /usr/bin/test -d "$CHECKPATH"
    if [[ $? == 1 ]]; then
        echo "Create: $CHECKPATH"
        /usr/bin/sudo -u dbuser /usr/bin/mkdir -p "$CHECKPATH"
    fi

done
```

Running this I get the following error:

```
/usr/bin/mkdir: cannot create directory ‘/home/dbuser/dropbox/example1’: No such file or directory
/usr/bin/mkdir: cannot create directory ‘/home/dbuser/dropbox/example2’: No such file or directory
/usr/bin/mkdir: cannot create directory ‘/home/dbuser/dropbox/example3’: No such file or directory
```

Then oddly enough, looking in the dropbox folder example[1-3] all exist.

This is running on Fedora 28 with Python 3.6.5. 

Thanks in advance on the help with this, your project is a life saver what with the glibc changes.

**Comment by rianhunter** [comment]
Thanks for this bug report @JeffPsycle, very helpful.
