### ISSUE TITLE
[RFE] Add suport to other storage backends

### ISSUE THREAD

**Issue by aruiz** [rianhunter/dbxfs#2]
It'd be great to support Google Drive as well. Would you entertain the idea of abstracting the synchronization and fuse work and have a generic remote VFS layer so that more protocols could be added?

**Comment by rianhunter** [comment]
Hooking into the OS is already abstracted out: https://github.com/rianhunter/userspacefs

The caching layer is heavily catered to the Dropbox API and I think it would worsen the maintainability of that file to support different backends with different semantics. Free free to copy `dbxfs/cachingfs.py` and adapt it to Google Drive if you like.
