### ISSUE TITLE
Incomplete pull

### ISSUE THREAD

**Issue by nwalet** [rianhunter/dbxfs#21]
Occassionally, typically when trying to open a file within an application, an incomplete version of the file is added to the cache.
This may be a time-out. There seems to be no way to invalidate such a file, or force dbxfs to pull the file again, apart from  to download a copy of the file from dropbox through the web interface.
Is there a way to invalidate a file? Is there a way to see why this happens?
Niels

**Comment by rianhunter** [comment]
This should never happen. Can you provide the full verbose logs when opening and reading an incomplete file?

**Comment by rianhunter** [comment]
Any updates here? Otherwise I'll have to close this issue.

**Comment by nwalet** [comment]
Sorry, tried to trace anything log related, but couldn't see anything relevant.
May just be due to my rather weird set-up.
Niels

**Comment by rianhunter** [comment]
Can you reproduce the issue, or has it resolved itself?

**Comment by nwalet** [comment]
I still can--just opening a very large mathematica file usually does it.
The problem is that as a precompiled commercial application mathematica may be doing weird things in the filesystem, and my dbxfs runs inside an nfs4  environment, which also lacks some filesystem functionality.

**Comment by rianhunter** [comment]
I've fixed some bugs in the cache file handling, please upgrade to 1.0.43 and report back whether or not you are still seeing the same behavior.

**Comment by nwalet** [comment]
Will do, and will report back.

**Comment by rianhunter** [comment]
closing for now. if this issue re-emerges with more info, make a new issue
