### ISSUE TITLE
Uploading empty files

### ISSUE THREAD

**Issue by sundoulos2** [rianhunter/dbxfs#28]
openSuse Tumbleweed; python 3.6; dbxfs 1.0.41

I have two dropbox accounts - one "personal" and one "shared" (both are the Basic dropbox accounts). The "personal" account has only 1 user (me), the "shared" account has 3 users (me + 2 others, 1 of whom set up the account).

I have a mount point set up for each account, and a separate config file for each. I use lsyncd to sync a local folder with each mount point. The results are the same whether I run dbxfs for each mount point separately or simultaneously.

Using dbxfs to sync my "personal" accounts works as expected. It does not function properly with the "shared" account. There are at least 2 issues:

1. Once the "shared" account is synchronized, every time I run dbxfs , even though no file has changed since the last sync, dbxfs updates the date/time stamp on each file.

2. If I edit a file locally, dbxfs appears to do all the right stuff and replaces the file in the dropbox location, but the file has _zero bytes._ After syncing, files in the local mount point and in the dropbox location have the same date/time stamp; the local file is intact with the correct size, the uploaded file is empty. If I stop dbxfs, the local mount point folder is empty. When I restart dbxfs, everything reappears locally as it exists in the dropbox location.

For the "private" account, only files that have actually changed get updated and have their date/time stamp modified. Stopping dbxfs does not empty out the local mount point, restarting it does not update the date/time stamp on each file like with the "shared" account. For what it's worth, the two other people who share the account are happily running some version of Window$.

I _can_ use the web interface to upload files to the shared account but dbxfs would be a much simpler solution. Any help will be appreciated :-)

**Comment by rianhunter** [comment]
Thanks for the bug report. Sorry you're having some issues.

I'm not sure I understand all the issues you're having with your shared account. I think I understand everything until this sentence:

> Stopping dbxfs does not empty out the local mount point, restarting it does not update the date/time stamp on each file like with the "shared" account.

What is the "local mount point"? From the preceding statements, it seems like you are using a separate program to sync from a local directory to the dbxfs mount point of the shared account.

In any case, try running dbxfs for the shared account as with the flags "-vv -f" and run a sync with lsyncd. Paste the result here (make sure to redact any private info) and we should be able to get to the bottom of this.

**Comment by sundoulos2** [comment]
This is one set of commands I use:
lsyncd -rsync /home/mine/Dropbox/ /home/mine/Shared-Dropbox/
dbxfs -c /home/mine/.config/dbxfs/config-Shared.json -o nonempty

The .json file has this:
{"keyring_user": "somethingsomething", "asked_send_error_reports": true, "mount_point": "/home/mine/Shared-Dropbox"}

An update on the behavior:
1. dbxfs is running; 
2. modify a file in /home/mine/Dropbox/; 
3. lsyncd is running daemonized and syncs /home/mine/Dropbox/ to /home/mine/Shared-Dropbox/; 
4. dbxfs uploads a file with zero bytes to dropbox; 
5. kill the dbxfs process; 
6. /home/mine/Shared-Dropbox/ has no files in it; 
7. restart dbxfs; 
8. /home/mine/Shared-Dropbox/ has the files in it as existing in the dropbox location including the file with zero bytes; 
9. kill the dbxfs process again; 
10. files are still present in /home/mine/Shared-Dropbox/

The commands and .json file for the Personal account are the same except the keyring entry, directory and mount point names. Results for the Personal account are that files are uploaded intact, killing the process does not affect the contents of the mount point.

I'll try the command with the flags and report back.

**Comment by rianhunter** [comment]
So you're automatically syncing from your personal account to the shared account?

In step 10, those files present in the shared mount point might be stored on your disk. Probably put by lsyncd when the dbxfs instance of the shared account was not running. It's not good practice to mount with "-o nonempty," otherwise you get confusing situations like that. I would run "chmod a-w /home/mine/Shared-Dropbox" when dbxfs is not running there to prevent accidental writing to the mount point.

**Comment by sundoulos2** [comment]
> So you're automatically syncing from your personal account to the shared account?

That is correct.

> In step 10, those files present in the shared mount point might be stored on your disk. Probably put by lsyncd when the dbxfs instance of the shared account was not running. It's not good practice to mount with "-o nonempty," otherwise you get confusing situations like that. I would run "chmod a-w /home/mine/Shared-Dropbox" when dbxfs is not running there to prevent accidental writing to the mount point.

If I run dbxfs without the "-o nonempty" I get this message:

fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
Unable to mount file system

In practice, this is safe enough because I am the only one modifying the files. The other 2 people who share the account only read the files. They are mp3 files that I produce for a radio program, the others who share the account only copy them to their server for air play.

**Comment by rianhunter** [comment]
Hmm. The mountpoint being empty has nothing to do with what dbxfs is doing. It's not good practice to mount file systems on top of non-empty directories. Why do you have files there if you intend for that to be your dbxfs mount point?

**Comment by sundoulos2** [comment]
They are the ones dbxfs put there during sync and remain (some of the time) when the process is killed.

Running dbxfs with -vv -f made quite the mess! Tons of output to the console and files with zero bytes in the dropbox location. Grr!

**Comment by sundoulos2** [comment]
If I "chmod a-w" then I get this message:

fusermount: user has no write access to mountpoint /home/mine/Shared-Dropbox
Unable to mount file system

**Comment by rianhunter** [comment]
Ah, that's unfortunate. I still would never use "-o nonempty"

**Comment by sundoulos2** [comment]
> If you don't want lsyncd to erroneously drop files in your mountpoint when dbxfs is not running (and I don't think you do) you should prevent writing to your mountpoint with "chmod a-w /home/mine/Shared-Dropbox".

That's exactly what I **do** want to happen. Then dbxfs should upload any changed files to dropbox when it runs.

That is the way it works on my Personal account (even with the "-o nonempty" parameter). It would be nice if it worked the same on the Shared account.

**Comment by rianhunter** [comment]
> That's exactly what I **do** want to happen (that's the way the dropbox linux client worked). Then dbxfs should upload any changed files to dropbox when it runs.

dbxfs will not do this, it doesn't work like the dropbox linux client. it works like a file system mount. file system mounts are unaware of files that live under their mount points. dbxfs must be running for it to transfer files.

**Comment by sundoulos2** [comment]
I understand that it must be running to transfer files. What I don't understand is why it replaces changed files with ones of zero bytes on one account and not the other. Guess I need to look for a different way to keep things synchronized. Maybe rclone will get me there. I've spent too much time already trying to figure this out and the radio schedule won't wait!

**Comment by rianhunter** [comment]
Okay if you aren't going to provide logs please close this issue.
