### ISSUE TITLE
Config file location

### ISSUE THREAD

**Issue by sk8nfool** [rianhunter/dbxfs#29]
How about trying to open the config file in the default location if the path supplied by -c fails to open? This way one could say "dbxfs -c jabber.json" from anywhere and /home/xxx/.config/dbxfs/jabber.json would be used.

**Comment by rianhunter** [comment]
I think this complicates things too much. Since the under normal usage the dbxfs command is rarely invoked, the user should just supply the full path to the config file.

**Comment by rianhunter** [comment]
> 1. "the dbxfs command is rarely invoked" - How so? The command is saved in a local folder ($HOME/.local/dbxfs/bin) and if the user has an encrypted home then putting something in /etc/fstab doesn't work reliably (I'm using Ubuntu). How else is the command invoked?

I just mean that you only invoke the `dbxfs` command once per session. Most often inside some sort of startup shell script. If that's the case, there is no urgent need to for "command line ergonomics" like this. 

> 2. "this complicates things too much" - Again How so? It's much easier to say "dbxfs -c xxx.json" than "dbxfs -c ~/.config/dbxfs/xxx.json". In fact it would be easier to just say "dbxfs -c xxx". Any complication is in you code since you'd have to add logic to handle prefixing of "~/.config/dbxfs" and postfixing ".json" when just opening the specified file fails but adding this would make dbxfs more user friendly.

Yes it would be easier to just write `dbxfs -c xxx` but a lot of things would make it easier to use. Why not just add every conceivable option that would make things easier for any user who asks for them? Instead the philosophy is to provide essential bare-bones functionality and the user can tailor that to their needs. This is the unix way. It's not hard to write a shell script called `dbxcfg` that does this:

    dbxfs -c $(dbxcfg xxx)

Or even easier `mydbxfs`:

    mydbxfs -c xxx

**Comment by sk8nfool** [comment]
And I thought this was a discussion about a suggestion. Somehow it got to
be about religion! The Unix Way trumps everything therefore no need to ....

On Jan 10, 2019 4:37 PM, "Rian Hunter" <notifications@github.com> wrote:


   1. "the dbxfs command is rarely invoked" - How so? The command is saved
   in a local folder ($HOME/.local/dbxfs/bin) and if the user has an encrypted
   home then putting something in /etc/fstab doesn't work reliably (I'm using
   Ubuntu). How else is the command invoked?

I just mean that you only invoke the dbxfs command once per session. Most
often inside some sort of startup shell script. If that's the case, there
is no urgent need to for "command line ergonomics" like this.


   1. "this complicates things too much" - Again How so? It's much easier
   to say "dbxfs -c xxx.json" than "dbxfs -c /.config/dbxfs/xxx.json". In
   fact it would be easier to just say "dbxfs -c xxx". Any complication is in
   you code since you'd have to add logic to handle prefixing of
"/.config/dbxfs"
   and postfixing ".json" when just opening the specified file fails but
   adding this would make dbxfs more user friendly.

Yes it would be easier to just write dbxfs -c xxx but a lot of things would
make it easier to use. Why not just add every conceivable option that would
make things easier for any user who asks for them? Instead the philosophy
is to provide essential bare-bones functionality and the user can tailor
that to their needs. This is the unix way. It's not hard to write a shell
script called dbxcfg that does this:

dbxfs -c $(dbxcfg xxx)

Or even easier mydbxfs:

mydbxfs -c xxx

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rianhunter/dbxfs/issues/29#issuecomment-453263254>, or mute
the thread

**Comment by sk8nfool** [comment]
I understand pragmatism. I also understand user friendliness. Isn't what I
suggest just an extension of what your design already does? You already
place the default .json file in a place you don't document (where's the man
page?). You had to add a parameter with a name 27 characters long to let
the user know where you squirreled it away. And no short version. This may
be a bit too pragmatic.

**Comment by rianhunter** [comment]
Are you offering to contribute a man page?

**Comment by sk8nfool** [comment]
Not really - I didn't write the app so I could only go by what '-h' says and maybe what your readme files say.
BTW - I really like the fact that you included your design description.
