### ISSUE TITLE
Unable to mount file system

### ISSUE THREAD

**Issue by JSybrandt** [rianhunter/dbxfs#3]
I installed this on two ubuntu machines and it worked perfectly.
But I'm trying to install on a third w/ a different OS and I'm seeing "Unable to mount file system"
Any clue what could be causing this?

**Comment by rianhunter** [comment]
What's the console say? Most likely you don't have the `libfuse2` package installed.

**Comment by rianhunter** [comment]
Try upgrading dbxfs:

    $ pip3 install --upgrade dbxfs

And then run via:

    $ dbxfs -vv -f

Post the output here, maybe it will help figure out what's wrong.

I will close this issue if there is no response in 1 week.

**Comment by bekoeppel** [comment]
I got the same error message on Ubuntu 16.04. The reason was that my mount point was owned by `root` and had permissions `700`, while I was trying to mount `dbxfs` as user `beni`. Changing ownership of the mount point to `beni`, mounting worked.

However, `dbxfs -vv` did not print out any error about the permissions.

**Comment by rianhunter** [comment]
@bekoeppel Hmm I just recreated those conditions and I get this output

    $ dbxfs test
    fuse: failed to open mountpoint for reading: Permission denied
    Unable to mount file system

**Comment by bekoeppel** [comment]
You're right, I must have been blind :+1:

**Comment by JSybrandt** [comment]
Hey, sorry I havn't been responsive.

I just tried the update and had to refresh my config.
Heres the log, minus the token
I have fuze  2.9.7 installed

There is a new error this time


```
$ dbxfs dropbox/
Failed to get most recent version
Traceback (most recent call last):
  File "/home/jsybran/.local/lib/python3.4/site-packages/dbxfs/main.py", line 107, in _main
    if json.load(f)['info']['version'] != version:
  File "/software/python/3.4/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/software/python/3.4/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
We need an access token. Perform the following steps:
1. Go to https://www.dropbox.com/oauth2/authorize?response_type=code&client_id=iftkeq2y4qj0nbt
2. Click "Allow" (you may have to log in first)
3. Copy the authorization code.
Enter authorization code (Ctrl-C to quit): XXXXXXXXXXXXXXXXX
We're all connected. Do you want to save your credentials for future runs? [Y/n] Y
We need a passphrase to encrypt your access token before we can save it.
Warning: Your access token passphrase must contain enough randomness to be resistent to hacking. You can read this for more info: https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/
Enter new access token passphrase: 
Enter new access token passphrase (again): 
Would you like to help us improve dbxfs by providing anonymous error reports? [Y/n] Y
Do you want "dropbox/" to be the default mount point? [Y/n] Y
Unable to mount file system
```

**Comment by rianhunter** [comment]
Two issues:

1. It looks like you have an old version of python installed, dbxfs requires python 3.5+
2. Are you 100% sure you have fuse installed? dbxfs doesn't seem like it's able to find it..

**Comment by JSybrandt** [comment]
Thank you!
I had some awkward dependency issues. I'm not the admin on the system I was attempting to use, and while python3.6 was my default, dbxfs was installed under 3.4. 
Once I sorted that it worked!
