### ISSUE TITLE
is there a keepalive function?

### ISSUE THREAD

**Issue by devuserlutions** [rianhunter/dbxfs#31]

**Comment by devuserlutions** [comment]
Dear Rian, I want to use dbxfs on a debian server to backup files and folders. Sometimes the mount point is empty, maybe because of a lost internet connection, or some kind of timeout.
I know this might not be a real issue, but sorry I have no twitter account, and I really don't want one.
Using a script with crontab is a little difficult, as one would have to provide the password for the keyring somehow. Any advice on how to approach this topic? Kind regards, Jens.

**Comment by rianhunter** [comment]
Hi Jens, A keepalive option is not necessary. Dbxfs should continue to operate as expected even if internet goes down intermittently. If the mount point is incorrectly empty on your server sometimes then that is a bug. Could you provide the log next time that happens (use "-v" and check syslog)? If you wish you may send it to me privately.

**Comment by devuserlutions** [comment]
Hello Rian, I'll closely watch this, maybe it was just after a server restart. I'm experimenting with a testserver these days. As soon as it happens again, I'll write you here. 
Thank you very much for your quick answer. J.

**Comment by rianhunter** [comment]
closing this for now, if this issue re-emerges and there is more info make a new issue
