### ISSUE TITLE
Transfer Speeds?

### ISSUE THREAD

**Issue by Sumarious** [rianhunter/dbxfs#33]
I've recently setup dbxfs and mounted my Dropbox account on my Linux system.
But I'm experiencing very throttled speeds for some reason. I'm on a 200MB/s connection with 100MB/s upload and for some reason, dbxfs is only giving me about an average 30KiB/s. Often times the transfer will just hang and goto nothing then eventually continue. Taking days to upload about a 1gb file seems a little out of the ordinary.

Anyone else experiencing results like this?
Or able to offer any suggestions on how to increase performance?

**Comment by rianhunter** [comment]
I looked into this a bit and it may have something to do with this line:

https://github.com/rianhunter/dbxfs/blob/master/dbxfs/dbxfs.py#L384

Try decreasing that to `32 * 1024 * 1024` and see if that helps you.

**Comment by Sumarious** [comment]
Still about the same speeds.
Bounces around between 10-40KiB/s.

**Comment by rianhunter** [comment]
Ah, don't have any other obvious suggestions. Would need more research. I don't see slow upload speeds so it has something to do with your setup.

**Comment by webplease** [comment]
same problem here :(

**Comment by gwinans** [comment]
I'll also add that I'm peaking at 190kB/sec on a 1Gb pipe.

Prior to Dropbox doing a stupid and killing support for non-xfs file systems, the cli client had no issue hitting 30-50MB/sec.

Any form of data we can collect for you?

**Comment by rianhunter** [comment]
Are you quoting me long term average transfer speeds or instantaneous transfer speeds? Is the bandwidth graph over time spikey or flat? If it's relatively flat it's likely that this is not a problem with dbxfs itself, but that Dropbox is rate limiting dbxfs on the server side.

**Comment by gwinans** [comment]
Long-term flat, infact. Quick ramp to about 180-190kB/sec and holds rock steady.

I, too, suspect it's dropbox over dbxfs. With that said, dbxfs is significantly more user-friendly than their client. Luckily, my largest daily xfer is only about 200M. I'll probably move off to S3 in time.

**Comment by rianhunter** [comment]
That's interesting, I was getting 25MiB/s at one point so maybe they are rate limiting. Though it could be your specific route to them that is slow. Where are you located?

If you want, you could try using your own app key and secret and see if you still experience a limit.

**Comment by gwinans** [comment]
The instance itself is in Oregon (AWS, US-WEST-1).

Is there a config I need to modify for appkey/secret? I vaguely recall seeing it mentioned in the output during setup.

**Comment by rianhunter** [comment]
It's not a config, you'll have to modify the code itself for now:

https://github.com/rianhunter/dbxfs/blob/master/dbxfs/main.py#L62

**Comment by gwinans** [comment]
I'll give it a try and let you know shortly.

**Comment by gwinans** [comment]
Result: No change.

Is there a way to find the endpoint this talks to? Best I can think is try run mtr against it, see if the route sucks.

**Comment by rianhunter** [comment]
> EDIT: Insane packetloss to content.dropbox.com.

That's very interesting, maybe they are dropping mtr ping probes. You might want to run `tcpdump` while `dbxfs` is downloading to see if packet loss is occurring during a normal TCP transfer.

Also have you tried testing download speeds from your native location and not from AWS? Do you see the same level of `mtr` packet loss from there?

**Comment by rianhunter** [comment]
Another option is to try this tool: https://github.com/dropbox/dbxcli Is it as slow?

**Comment by gwinans** [comment]
dbxcli pushed the file at ~25MB/sec. Smells like throttling.

**Comment by rianhunter** [comment]
From the same server? If dbxcli outperformed dbxfs on the same server, then it's probably dbxfs though there is an unlikley chance they are sniffer User Agent.

**Comment by gwinans** [comment]
Same machine. Back-to-back, both show significant differences in performance.

**Comment by rianhunter** [comment]
Ah okay, so there is likely a problem in dbxfs. This will require more investigation, but I don't have any free time any time soon to investigate. Feel free to provide a PR

**Comment by dseeker** [comment]
Having same issue, if I manually copy the file url via browser inspector network link I can download at 300Mbps, but via dbxfs it only drips around 1Mbps when copying from the dropbox mount to local file system.

**Comment by maykel535** [comment]
I have a same problem... The copy file 100Mb over the dropbox map folder is 250Kb/s ... I don't understand.

**Comment by robot3498712** [comment]
Insanely slow here as well on debian 9.
Checked via netstat --all --program | grep '<PID>' && iftop -i enp1s0 -f "dst port <PORT>"
Flushing iptables did not help.
A connection to dropbox is alive, but speeds rarely exceed BITS per second. Totally unusuable in this state, whoever is to blame for this cockup.
Transfer does work however, for tiny files at least.

**Comment by JeffPsycle** [comment]
Oddly enough, I have seen a dramatic speed up since moving to CentOS 8 from Fedora 28.

**Comment by whittinghamj** [comment]
I just want to say that I'm seeing exactly the same on ubuntu 18.04

fresh install of OS and dbxfs - speeds are so slow that its pointless using this amazing app - come on dev team - fix this please !!!

**Comment by rianhunter** [comment]
@whittinghamj Would love to fix this but my time is limited, if you send 500 mBTC to 1Am6AZHzrRvejYR3wBjo3oG4xUnbCa51dM I can dedicate a day to fixing this.

**Comment by rianhunter** [comment]
if everyone in this thread is still having this issue, i suggest you organize a fund raiser. 500USD will get me to spend a day to fix this. If no one responds with any interest by tomorrow i will close this issue

**Comment by rianhunter** [comment]
closed due to lack of interest
