### ISSUE TITLE
Store Access Token and mount with fstab

### ISSUE THREAD

**Issue by webplease** [rianhunter/dbxfs#34]
Hi,

i have 2 questions:

1) is it possible to auto-mount dbxfs with fstab? How?
2) I have generate an access token from Dropbox developers app console, and store it into an encrypted gpg file (as described in your readme), and add "access_token_command" in config.json file. When I mount, GPG naturally asks me the password for decrypt. If i need to auto-mount (fstab) i can't insert that password, how can i solve?

Thanks very much!

**Comment by rianhunter** [comment]
There are dozens of tutorials online on how to automount fuse file systems with fstab. If you want to automount without a password, store the password in plaintext and change the access token command to just cat out the file.

**Comment by webplease** [comment]
hi rianhunter,

there's a problem changing the command:

With "access_token_command": ["gpg", "--passphrase mypwd --decrypt", "/home/admin/dropbox.gpg"]

not works :(

**Comment by rianhunter** [comment]
dbxfs is for technical users, you'll have to figure this one out on your own

**Comment by webplease** [comment]
leaving this problem (solvable), can you help me with the upload speed problem? Making a simple "cp" of a file on the mounted folder/dropbox I reach a transfer average of max 100Kb/sec ... do you have any idea what it might be?

**Comment by rianhunter** [comment]
I'm not sure, I haven't observed this myself but I'll look into it eventually. If you can fix it yourself and provide a PR that would be awesome.

**Comment by JamesMcGuigan** [comment]
Here was my solution for automount on Gnome Startup

In Ubuntu 18.04 Gnome, run the `dbxfs` command manually once and the decryption password popup should have checkbox to autosave the password for future use. 

A (slightly less secure) workaround is to store the access token unencrypted and replace `gpg --decrypt access_token.gpg` with `cat access_token`. Security wise, this may be acceptable for a single-user laptop, but at the very least run `chmod 600 access_token` (doesn't secure against software running as your user, or attackers with access to your hardware).

For the autostart script, I have found that `fusermount -q -u ~/Dropbox; sleep 2s;` is required a prefix to prevent dead mountpoints, and you need to pass `yes` to dbxfs to answer the question about a non-existant directory.



~/.config/autostart/dbxfs.desktop 
```
[Desktop Entry]
Type=Application
Exec=bash -c "fusermount -q -u ~/Dropbox; sleep 2s; yes | dbxfs"
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=dbxfs ~/Dropbox/
Name=dbxfs ~/Dropbox/
Comment[en_US]=Mount Dropbox
Comment=Mount Dropbox
```

cat ~/.config/dbxfs/config.json 
```
{
    "send_error_reports": true, 
    "asked_send_error_reports": true, 
    "mount_point": "/home/jamie/Dropbox/",
    "access_token_command": ["gpg", "--decrypt", "/home/jamie/.config/dbxfs/access_token.gpg"]
}
```
