### ISSUE TITLE
High load after upgrading from 1.0.36 to 1.0.43

### ISSUE THREAD

**Issue by JeffPsycle** [rianhunter/dbxfs#35]
I know this is a bit of a shot in the dark but I was hoping that maybe reaching out might pull in some  other options for determining the cause of this issue.

We are experiencing an issue that the load on 2+ load balanced web servers progressively creeps up until the instances become unusable. Running 1.0.36 it works just fine, but when I upgrade to 1.0.43 we start to experience the issue. It is not a high CPU issue causing the load but a IOWAIT where the Apache/Nginx processes hit a stalled state when I believe they are accessing the dbxfs mount. My thoughts are that it could possibly be a version of a Python package causing this because we have a separate machine that has a very similar setup to the web servers that is just for administrative tasks. It is running 1.0.43 but has some older versions of the Python packages.

Our process on AWS is to create an image from a staging instance that has all of our updates and then spin up we instances after updating the load balancer. I have tried manually sending in new instances but one after another they all hit a load of 30+ on a 4-core instance and then become nearly unresponsive. Unfortunately I did not save a screencap of glances running on one of the machines as it spiralled out of control. 

I am going to test if it is potentially one of these Python packages causing the issue on Wednesday when we have our window for performing system updates but I was hoping that maybe something would stand out.

Our machine with 1.0.43 that works well has the following:

```
dbxfs==1.0.43
  - appdirs [required: >=1.4,<2, installed: 1.4.3]
  - block-tracing [required: >=1.0.1,<2, installed: 1.0.1]
  - dropbox [required: >=3.38, installed: 9.3.0]
    - requests [required: >=2.16.2, installed: 2.21.0]
      - certifi [required: >=2017.4.17, installed: 2018.11.29]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.9, installed: 2.8]
      - urllib3 [required: >=1.21.1,<1.25, installed: 1.24.1]
    - six [required: >=1.3.0, installed: 1.12.0]
  - keyring [required: >=15.1.0, installed: 17.1.1]
    - entrypoints [required: Any, installed: 0.3]
    - secretstorage [required: Any, installed: 3.1.0]
      - cryptography [required: Any, installed: 2.4.2]
        - asn1crypto [required: >=0.21.0, installed: 0.24.0]
        - cffi [required: >=1.7,!=1.11.3, installed: 1.11.5]
          - pycparser [required: Any, installed: 2.19]
        - idna [required: >=2.1, installed: 2.8]
        - six [required: >=1.4.1, installed: 1.12.0]
      - jeepney [required: Any, installed: 0.4]
  - keyrings.alt [required: >=3.1,<4, installed: 3.1.1]
    - six [required: Any, installed: 1.12.0]
  - privy [required: >=6.0,<7, installed: 6.0.0]
    - argon2-cffi [required: Any, installed: 18.3.0]
      - cffi [required: >=1.0.0, installed: 1.11.5]
        - pycparser [required: Any, installed: 2.19]
      - six [required: Any, installed: 1.12.0]
    - cryptography [required: Any, installed: 2.4.2]
      - asn1crypto [required: >=0.21.0, installed: 0.24.0]
      - cffi [required: >=1.7,!=1.11.3, installed: 1.11.5]
        - pycparser [required: Any, installed: 2.19]
      - idna [required: >=2.1, installed: 2.8]
      - six [required: >=1.4.1, installed: 1.12.0]
  - sentry-sdk [required: >=0.3,<1, installed: 0.6.6]
    - certifi [required: Any, installed: 2018.11.29]
    - urllib3 [required: Any, installed: 1.24.1]
  - userspacefs [required: >=1.0.13,<2, installed: 1.0.13]
    - fusepyng [required: >=1.0.7,<2, installed: 1.0.7]
```

The machine(s) that hit a high load have the following:

```
dbxfs==1.0.43
  - appdirs [required: >=1.4,<2, installed: 1.4.3]
  - block-tracing [required: >=1.0.1,<2, installed: 1.0.1]
  - dropbox [required: >=3.38, installed: 9.3.0]
    - requests [required: >=2.16.2, installed: 2.21.0]
      - certifi [required: >=2017.4.17, installed: 2019.3.9]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.9, installed: 2.8]
      - urllib3 [required: >=1.21.1,<1.25, installed: 1.24.1]
    - six [required: >=1.3.0, installed: 1.12.0]
  - keyring [required: >=15.1.0, installed: 19.0.1]
    - entrypoints [required: Any, installed: 0.3]
    - secretstorage [required: Any, installed: 3.1.1]
      - cryptography [required: Any, installed: 2.6.1]
        - asn1crypto [required: >=0.21.0, installed: 0.24.0]
        - cffi [required: >=1.8,!=1.11.3, installed: 1.12.2]
          - pycparser [required: Any, installed: 2.19]
        - six [required: >=1.4.1, installed: 1.12.0]
      - jeepney [required: Any, installed: 0.4]
  - keyrings.alt [required: >=3.1,<4, installed: 3.1.1]
    - six [required: Any, installed: 1.12.0]
  - privy [required: >=6.0,<7, installed: 6.0.0]
    - argon2-cffi [required: Any, installed: 19.1.0]
      - cffi [required: >=1.0.0, installed: 1.12.2]
        - pycparser [required: Any, installed: 2.19]
      - six [required: Any, installed: 1.12.0]
    - cryptography [required: Any, installed: 2.6.1]
      - asn1crypto [required: >=0.21.0, installed: 0.24.0]
      - cffi [required: >=1.8,!=1.11.3, installed: 1.12.2]
        - pycparser [required: Any, installed: 2.19]
      - six [required: >=1.4.1, installed: 1.12.0]
  - sentry-sdk [required: >=0.3,<1, installed: 0.7.10]
    - certifi [required: Any, installed: 2019.3.9]
    - urllib3 [required: Any, installed: 1.24.1]
  - userspacefs [required: >=1.0.13,<2, installed: 1.0.13]
    - fusepyng [required: >=1.0.7,<2, installed: 1.0.7]
``` 

As I said, I don't believe this is a issue with dbxfs v1.0.43 itself as it is running quite happily on our one machine. It could be a combination of our use case, environment or I am hoping the Python modules. Thanks in advance for any insights you can give on diagnosing this.

**Comment by rianhunter** [comment]
No clue off the top of my head, I would suggest just reverting back to 1.0.36 and seeing if that helps. I would have to study the diff between the two versions and have a more in-depth understanding of your usage patterns to give you a specific answer. PRs welcome if you can pin down the issue :)

**Comment by JeffPsycle** [comment]
Sorry to the delayed response on this. I finally have been granted a window to test this next week. Will post an update when I see if there is a correlation to the particular set of modules.

**Comment by JeffPsycle** [comment]
Apologies that it has been an eternity since replying on this. I suspect that it is an environment issue in conjunction with a dependant Python package change. You might recall from a prior issue that we are using EFS on AWS for the cache files so multiple servers can use the same cache files. This EFS mount was also used for the docroot for apache/nginx. AWS just added a new cloudwatch metric showing the max I/O percentage utilised and it was shown that with our current setup we were pinning the I/O. Having spit the network storage for cache files from the docroot we have seen a massive improvement.
