### ISSUE TITLE
RequestsDependencyWarning

### ISSUE THREAD

**Issue by yochananmarqos** [rianhunter/dbxfs#36]
I now receive this warning after `python-urllib3` updated:
```
/usr/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```

**Comment by rianhunter** [comment]
Hmm, what would you suggest is the best fix?

**Comment by yochananmarqos** [comment]
I'm not sure, but I'll wait until `python-requests` 2.22.0 rolls out to me and see if if still happens. It looks like this issue should have been fixed [a year ago](https://github.com/kennethreitz/requests/pull/4671).

**Comment by yochananmarqos** [comment]
The update to python-requests 2.22.0 fixed the issue.
