### ISSUE TITLE
How do I access admin console?

### ISSUE THREAD

**Issue by bk322** [rianhunter/dbxfs#37]
Hi,

I'm using dropbox for business. I have my own account, and I also happen to be the admin, and so I have admin console. If I mount via dbxfs I get only my own folder. Is there a way to mount organization's view, that is my admin console?

**Comment by rianhunter** [comment]
Hmm I'm not totally sure. It might require a minor change to the code to use the admin root vs the user root. My time is limited so I cannot personally look into this in the near future but if you throw 25 mBTC I'll check it out. 1Am6AZHzrRvejYR3wBjo3oG4xUnbCa51dM

**Comment by akshayknz** [comment]
No

**Comment by rianhunter** [comment]
closing out of lack of interest
