### ISSUE TITLE
Is it possible to point mount to a specific Dropbox folder?

### ISSUE THREAD

**Issue by sunk818** [rianhunter/dbxfs#38]
I followed the directions here:
https://www.ostechnix.com/dbxfs-mount-dropbox-folder-locally-as-virtual-file-system-in-linux/

I was able to mount it successfully after updating pip3 to the latest.

I can see the root of my Dropbox folder, but is it possible to point to a specific folder?

My use case is to use spot instances where I can keep my work tasks on Dropbox and not lose data when the spot instance terminates.

**Comment by rianhunter** [comment]
This is currently not possible, dbxfs exposes the entire dropbox folder. If you only want to expose a specific hierarchy of the dropbox folder you can use a Linux bind mount.
