### ISSUE TITLE
Question: Would it be possible to use a custom API that mimics the dropbox api?

### ISSUE THREAD

**Issue by butsjoh** [rianhunter/dbxfs#4]
Hi, I would like to understand how tightly this is coupled to the functionality of dropbox. Would there be a way to make it more independed from it and for example swap out the dropbox (core api) with a custom made one (that implements the same abilities as the dropbox core api)? Just wondering

**Comment by rianhunter** [comment]
Anything is possible :) Though if you'd like to use a different backend, there are other options out there like rclone
