### ISSUE TITLE
safefs extra requirement does not exist anymore

### ISSUE THREAD

**Issue by orendorff-mi** [rianhunter/dbxfs#41]
Hello,

It appears that the `safefs` extra requirement does not exist anymore. There is a package on PyPi listed for safefs but no version of safefs uploaded onto PyPi has the same functions/classes that are imported in `safefs_glue.py`.

Is there some copy of this original package or an updated requirement that could be used instead?

**Comment by rianhunter** [comment]
`safefs` is a private package, and it's presence in `setup.py` is for my personal convenience.
