### ISSUE TITLE
Cannot create regular file - invalid argument

### ISSUE THREAD

**Issue by po-stas** [rianhunter/dbxfs#44]
Hello Rian!
Trying to copy several pretty large files to Dropbox. Ubuntu 18.04 LTS
When Dbxfs mounted, everything starts just fine. 
cp starts to copy... after copying one or two files (about 500Mb), I get the following errors:
cp: cannot create regular file 'backup/dropbox/HerebroBackup/OFGH.garbador.catalog/OFGH Online 2014/2014-04-23/zapr.tiff': Invalid argument..

This error can appear after copying the first file or after several files has been copied... but overall I couldn't copy more than 5-6 files.

Same with rsync:
rsync: mkstemp "/home/ubuntu/backup/dropbox/HerebroBackup/OFGH.garbador.catalog/GeneralMaterials/.tube_cavity.tif.nGW6en" failed: Invalid argument (22)

The mount staying alive all the time. I can browse the directories and read the files...

What could be wrong?

**Comment by po-stas** [comment]
Well, actually I've realized, that the reason was - zero space left on /tmp... for some reason /tmp dir is filling up during large transfers (and not being freed after file upload ends)
The only option is to specify --cache-dir but my drive is very limited in space. 2GB of free space filling up after an half an hour of transfer...

**Comment by rianhunter** [comment]
Yes this problem is somewhat known but I don't have the time to investigate at the moment. Feel free to submit a PR or I can fix it if you send me $1000, or $100/day

**Comment by rianhunter** [comment]
Fixed in  ba302ed
