### ISSUE TITLE
Segmentation fault when I do dbxfs ~/Dropbox

### ISSUE THREAD

**Issue by uuccio** [rianhunter/dbxfs#46]
Hi Ryan,
I'm a linux newbie... running Linux Mint 19.3   I installed dbxfs via anaconda, then created an empty Dropbox directory.  When I do dbxfs ~/Dropbox, I get Segmentation fault (core dumped).
I'm not sure what other information I can provide to help debug this.
Sacha

conda list dbxfs
# packages in environment at /home/sacha/anaconda3:
#
# Name                    Version                   Build  Channel
dbxfs                     1.0.43                     py_0    conda-forge
(base) sacha@sacha-MSI7:~$ dbxfs ~/Dropbox
Segmentation fault (core dumped)
(base) sacha@sacha-MSI7:~$

**Comment by rianhunter** [comment]
Report this to the package maintainer.

**Comment by uuccio** [comment]
Who is the package maintainer. I thought it was you.

**Comment by rianhunter** [comment]
I maintain the upstream source, check the package maintainer of the anaconda package. I don't see this problem on my setup so it must be specific to anaconda

**Comment by uuccio** [comment]
I see... There is actually no anaconda package specifically, it was my
(incompetent) attempt to install it on my linux mint machine.  I'll keep on
trying.

**Comment by rianhunter** [comment]
try starting it with gdb so you can get the backtrace of the segmentation fault.
