### ISSUE TITLE
Rename causes error

### ISSUE THREAD

**Issue by quiversky** [rianhunter/dbxfs#47]
In Nautilus, pressing F2 to rename any file longer than 1 character inside the mounted dropbox drive causes a "Filename too long" error.

**Comment by rianhunter** [comment]
Thanks for the report, I don't use nautilus so if you want this fixed you'll have to do it yourself. If you have the funds, I'm available for contract, please contact offline

**Comment by quiversky** [comment]
Who maintains this?

⁣Get BlueMail for Android ​

**Comment by rianhunter** [comment]
I do, but maintenance is not free

**Comment by quiversky** [comment]
I could make a contribution, if that would help. 

⁣Get BlueMail for Android ​

**Comment by rianhunter** [comment]
It would be best if you tried to debug it yourself but if you don't have the time, shoot me an email with your exact setup and if the issue sounds fixable, send me a day's work of pay and I'll spend a day within the next week fixing it.

**Comment by quiversky** [comment]
I would, except I'm not a python dev. Also, the error text appears nowhere in your code, so it's a nautilus error caused by something in the python code.

Anyway, best of luck.

⁣Get BlueMail for Android ​

**Comment by rianhunter** [comment]
closing out of lack of interest
