### ISSUE TITLE
Won't run on new Ubuntu 20.04 install

### ISSUE THREAD

**Issue by FastThenLeft** [rianhunter/dbxfs#54]
Running python3.8, pip3, libfuse2. Ran "sudo pip3 install dropbox" and it was already installed.

When I run dbxfs I get:
$ dbxfs ~/mydropbox
Traceback (most recent call last):
  File "/usr/local/bin/dbxfs", line 5, in <module>
    from dbxfs.main import main
  File "/usr/local/lib/python3.8/dist-packages/dbxfs/main.py", line 47, in <module>
    from dbxfs.dbxfs import FileSystem as DropboxFileSystem
  File "/usr/local/lib/python3.8/dist-packages/dbxfs/dbxfs.py", line 285, in <module>
    from dropbox.dropbox import RouteResult, RouteErrorResult
ModuleNotFoundError: No module named 'dropbox.dropbox'

What am I missing? Thanks!

**Comment by rianhunter** [comment]
Seems like we were using a non-public import that was broken in the newest version of the dropbox client and we didn't have an upper cap on version.  This is easy to fix since the reason we were using the non-public import was to use functionality not yet available at the time but is available now. If you're impatient just remove the `dbrequest()` calls with calls to the official SDK otherwise you'll have to wait for a fix.

**Comment by FastThenLeft** [comment]
Thank you so much for getting back to me so quickly! I spent hours working on this thinking it was me.

Unfortunately I don't quite know enough yet (I'm learning Python) to make the modification you suggested. Hopefully in the future I can help with this project! So in the meantime, I'll wait for the fix.

Thank you again for such a great app! I have it running on a different laptop (which I have now figured out is running an earlier version of the dropbox library which is why it works).

**Comment by rianhunter** [comment]
I'll fix this for you sometime this week but it takes up the little time I have for my other work so please throw some mBTC my way: 1Am6AZHzrRvejYR3wBjo3oG4xUnbCa51dM

**Comment by tanasegabriel** [comment]
You can just pin to an older version of `dropbox`, as a short term fix. So a one liner for this would be:

```
 pip3 install 'dropbox==10.10.0' dbxfs
```

**Comment by FastThenLeft** [comment]
Thanks!

**Comment by DaffyDuke** [comment]
> ```
>  pip install 'dropbox==10.0.0' dbxfs
> ```

fine, thakn you !
