### ISSUE TITLE
Mount point permissions issues under OpenBSD 6.8/amd64-stable

### ISSUE THREAD

**Issue by morgant** [rianhunter/dbxfs#60]
I successfully installed `dbxfs` on OpenBSD 6.8/amd64-stable as follows:

```
doas pkg_add py3-pip
doas pip3 dbxfs
```

And can mount as follows:

```
mkdir ~/Dropbox
doas dbxfs -o uid=1000 ~/Dropbox
```

However, the permissions on the `~/Dropbox` directory are changed to `700 root:wheel` and so the contents are not readable by the user with uid 1000, despite all the files & directories within `~/Dropbox` being correctly owned by the user with uid 1000:

```
drwx------   1 root       wheel         512 Jan 18 21:04 Dropbox
```

```
drwxrwxrwx   1 username  wheel              0 Jan 18 21:07 Apps
drwxrwxrwx   1 username  wheel              0 Jan 18 21:07 Camera Uploads
```

This does not occur when using the `-o uid=1000` option with other `fuse` FSes. Also, the permissions on `~/Dropbox` revert to their correct original permissions upon executing `doas umount ~/Dropbox`.

**Comment by rianhunter** [comment]
Just want to note that the issues tracker is not a support forum. Solutions here are not easily accessible by others. `dbxfs` is intended for computer experts that can read source code and solve their own issues.

You need to use `-o allow_other`. The negative security implications here are a shortcoming of OpenBSD's implementation of FUSE.

**Comment by morgant** [comment]
My sincerest apologies for the noise. I thought this was a bug, but clearly hadn't researched it well enough.

I do now see the `allow_other` option in [fuse_mount(3)](http://man.openbsd.org/fuse_mount.3) and `-o allow_other,uid=1000` does work, though setting permissions to `777`, as you note. I'm aware that OpenBSD's FUSE implementation leaves some things to be desired.

I greatly appreciate your work on this project, your work to support OpenBSD, and your quick responses.

**Comment by rianhunter** [comment]
You're welcome
