### ISSUE TITLE
Application uses too much memory

### ISSUE THREAD

**Issue by ancwrd1** [rianhunter/dbxfs#61]
OS: openSUSE Tumbleweed x86_64

When using a mounted Dropbox folder with many files and folders (browsing via Dolphin, copying files back and forth) the memory usage of the application grows exponentially.

See the attached screenshot:
![dbxfs-mem](https://user-images.githubusercontent.com/2361919/106494879-41c4a380-64bb-11eb-8986-8fb3c5e9f900.png)

Not sure if this is actually an upstream fuse issue or something with dbxfs.

**Comment by rianhunter** [comment]
Thanks for this report, the issue has been identified a fix should be released soon.

**Comment by JeffPsycle** [comment]
Also seen on CentOS 8 x86_64
