### ISSUE TITLE
Please add an option to disable caching.

### ISSUE THREAD

**Issue by ytrezq** [rianhunter/dbxfs#62]
Every files in my Dropbox account far exceed the available disk capacity.

How to avoid caching failing and use everything online just like with samba or nfs?

**Comment by rianhunter** [comment]
If you disk capacity is being filled up that is a bug. What version are you using?

**Comment by rianhunter** [comment]
If your disk capacity is being filled up that is a bug. What version are you using?

**Comment by ytrezq** [comment]
I simply don’t want to use caching. Whatever the reason, please just provide an option to disable any writing to disk.

**Comment by rianhunter** [comment]
> Whatever the reason, please just provide an option to disable any writing to disk.

Sorry not happening.
