### ISSUE TITLE
Comparision to rclone

### ISSUE THREAD

**Issue by ad-m** [rianhunter/dbxfs#8]
An interesting project. I wonder what is his advantage over rclone ( see https://rclone.org/commands/rclone_mount/ , https://rclone.org/cache/ ) which support Dropbox ( https://rclone.org/dropbox/ )?

**Comment by rianhunter** [comment]
dbxfs caches both metadata and file data and isn't experimental. it's more catered to dropbox's API, e.g. it uses dropbox's list_folder API to keep its cache up to date. you can use rsync on dbxfs mounts directly. dbxfs doesn't need FUSE on macOS.
